output "alias" {
    description = "Alias name for AWS Resources"
  value={
  "netgw": "igw",
  "natgw": "natgw",
  "vpc": "vpc",
  "eip": "eip",
  "subnet": "snet",
  "ec2": "vm",
  "routetable": "rtbl",
  "s3bucket": "bucket",
  "cloudwatch_loggroup": "clw-lggrp",
  "flowlog": "flowlog",
  "ebs": "ebs",
  "ebssnapshot": "snapshot",
  "asg": "asg",
  "launch_template": "lnch-tpl",
  "sg": "sgrp",
  "rds_subnet_group": "rds-subnet",
  "rds_parameter_group": "rds-parameter",
  "rds_option_group": "rds-option",
  "rds_instance": "rds-instance",
  "nacl": "nacl",
  "redshift_subnet_group": "rs-subnet",
  "elasticache_subnet_group": "ecache-subnet",
  "customer_gateway": "cgtw",
  "vpn_gateway": "vgtw",
  "egress_only_internet_gateway": "enetgw",
  "dhcp_options": "dhcp",
  "iamrole": "role",
  "iampolicy": "policy",
  "iamuser": "user",
  "iamgroup": "group",
  "alb": "alb",
  "elb": "elb",
  "nlb": "nlb",
  "tgrp": "tgrp",
  "lstnr": "lstnr",
  "peer": "peering",
  "tgw": "tgw",
  "ram": "ram",
  "aurora_cluster_instance": "aurora-inst",
  "aurora_cluster": "aurora-clus"
}

}
